In [28]:
import pandas as pd

df_zhvf_growth = pd.read_csv('../data/zhvf_growth.csv')

In [29]:
df_zhvf_growth.head()

,RegionID,SizeRank,RegionName,RegionType,StateName,State,City,Metro,CountyName,BaseDate,2025-11-30,2026-01-31,2026-10-31
0,91982,1,77494,zip,TX,TX,Katy,"Houston-The Woodlands-Sugar Land, TX",Fort Bend County,2025-10-31,0.2,0.1,0.1
1,61148,2,8701,zip,NJ,NJ,Lakewood,"New York-Newark-Jersey City, NY-NJ-PA",Ocean County,2025-10-31,0.7,1.0,2.3
2,91940,3,77449,zip,TX,TX,Katy,"Houston-The Woodlands-Sugar Land, TX",Harris County,2025-10-31,-0.2,-0.6,-0.3
3,62080,4,11368,zip,NY,NY,New York,"New York-Newark-Jersey City, NY-NJ-PA",Queens County,2025-10-31,0.1,0.2,0.8
4,91733,5,77084,zip,TX,TX,Houston,"Houston-The Woodlands-Sugar Land, TX",Harris County,2025-10-31,-0.3,-0.5,-0.3

In [30]:
dallas_zips = df_zhvf_growth[(df_zhvf_growth['City'] == "Dallas") & (df_zhvf_growth['State'] == "TX")]

In [31]:
dallas_zips['RegionName']

80       75217
167      75228
283      75243
435      75227
719      75216
839      75287
1471     75220
2053     75231
2205     75206
2316     75224
2391     75248
3008     75229
3094     75214
3209     75232
3229     75208
3293     75204
3347     75238
3423     75241
4453     75252
4519     75212
4529     75254
4837     75230
5172     75218
5271     75240
5277     75219
5533     75253
5807     75237
6428     75235
6804     75249
7037     75236
7042     75201
7286     75233
7477     75203
7521     75215
7676     75209
7834     75223
8321     75244
9566     75210
11900    75226
13141    75202
15582    75246
Name: RegionName, dtype: int64

In [32]:
# --- Aggregate and sort counties by projected growth ---
# Assuming the columns represent projected growth values for different dates
growth_columns = ["2025-11-30", "2026-01-31", "2026-10-31"]  # Replace with actual column names

# Calculate the aggregated growth (e.g., sum or average) for each county
dallas_zips["Aggregated_Growth"] = dallas_zips[growth_columns].mean(axis=1)

# Sort counties by aggregated growth
sorted_counties = dallas_zips.sort_values(by="Aggregated_Growth", ascending=False)

# Display the top counties with the highest aggregated growth
print("Top counties with good aggregated projected growth:")
print(sorted_counties[["RegionName", "Aggregated_Growth"]].head(10).to_markdown(index=False))

Top counties with good aggregated projected growth:
|   RegionName |   Aggregated_Growth |
|-------------:|--------------------:|
|        75220 |            0.833333 |
|        75209 |            0.533333 |
|        75230 |            0.5      |
|        75229 |            0.5      |
|        75246 |            0.433333 |
|        75244 |            0.433333 |
|        75218 |            0.433333 |
|        75238 |            0.333333 |
|        75201 |            0.3      |
|        75214 |            0.266667 |

C:\Users\megha\AppData\Local\Temp\ipykernel_4180\150896804.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dallas_zips["Aggregated_Growth"] = dallas_zips[growth_columns].mean(axis=1)

In [33]:
# --- Sort counties by bottom-tier ZHVI ---
# Assuming the columns represent bottom-tier ZHVI values for different dates
zhvi_columns = ["2025-11-30", "2026-01-31", "2026-10-31"]  # Replace with actual column names

# Calculate the average bottom-tier ZHVI for each county
dallas_zips["Average_Bottom_Tier_ZHVI"] = dallas_zips[zhvi_columns].mean(axis=1)

# Sort counties by the lowest average bottom-tier ZHVI
sorted_counties = dallas_zips.sort_values(by="Average_Bottom_Tier_ZHVI", ascending=True)

# Display the top counties with the lowest bottom-tier ZHVI
print("Top counties with the lowest bottom-tier ZHVI (affordable for first-time buyers):")
print(sorted_counties[["RegionName", "Average_Bottom_Tier_ZHVI"]].head(10).to_markdown(index=False))

Top counties with the lowest bottom-tier ZHVI (affordable for first-time buyers):
|   RegionName |   Average_Bottom_Tier_ZHVI |
|-------------:|---------------------------:|
|        75202 |                  -1.13333  |
|        75210 |                  -0.933333 |
|        75203 |                  -0.9      |
|        75235 |                  -0.866667 |
|        75216 |                  -0.8      |
|        75253 |                  -0.733333 |
|        75232 |                  -0.7      |
|        75217 |                  -0.7      |
|        75237 |                  -0.666667 |
|        75287 |                  -0.566667 |

C:\Users\megha\AppData\Local\Temp\ipykernel_4180\1114966291.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dallas_zips["Average_Bottom_Tier_ZHVI"] = dallas_zips[zhvi_columns].mean(axis=1)

In [34]:
# --- Sort counties by mid-tier ZHVI ---
# Assuming the columns represent mid-tier ZHVI values for different dates
zhvi_columns = ["2025-11-30", "2026-01-31", "2026-10-31"]  # Replace with actual column names

# Calculate the average mid-tier ZHVI for each county
dallas_zips["Average_Mid_Tier_ZHVI"] = dallas_zips[zhvi_columns].mean(axis=1)

# Sort counties by the lowest average mid-tier ZHVI
sorted_counties = dallas_zips.sort_values(by="Average_Mid_Tier_ZHVI", ascending=True)

# Display the top counties with the lowest mid-tier ZHVI
print("Top counties with the lowest mid-tier ZHVI (affordable for mid-range buyers):")
print(sorted_counties[["RegionName", "Average_Mid_Tier_ZHVI"]].head(10).to_markdown(index=False))

Top counties with the lowest mid-tier ZHVI (affordable for mid-range buyers):
|   RegionName |   Average_Mid_Tier_ZHVI |
|-------------:|------------------------:|
|        75202 |               -1.13333  |
|        75210 |               -0.933333 |
|        75203 |               -0.9      |
|        75235 |               -0.866667 |
|        75216 |               -0.8      |
|        75253 |               -0.733333 |
|        75232 |               -0.7      |
|        75217 |               -0.7      |
|        75237 |               -0.666667 |
|        75287 |               -0.566667 |

C:\Users\megha\AppData\Local\Temp\ipykernel_4180\964634663.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dallas_zips["Average_Mid_Tier_ZHVI"] = dallas_zips[zhvi_columns].mean(axis=1)

In [35]:
# --- Filter and sort counties by positive bottom-tier ZHVI aggregates ---
# Assuming the columns represent bottom-tier ZHVI values for different dates
zhvi_columns = ["2025-11-30", "2026-01-31", "2026-10-31"]  # Replace with actual column names

# Calculate the average bottom-tier ZHVI for each county
dallas_zips["Average_Bottom_Tier_ZHVI"] = dallas_zips[zhvi_columns].mean(axis=1)

# Filter counties with positive aggregates
dallas_zips_positive = dallas_zips[dallas_zips["Average_Bottom_Tier_ZHVI"] > 0]

# Sort counties by the lowest average bottom-tier ZHVI
sorted_counties = dallas_zips_positive.sort_values(by="Average_Bottom_Tier_ZHVI", ascending=False)

# Display the top counties with positive bottom-tier ZHVI aggregates
print("Top counties with positive bottom-tier ZHVI aggregates (affordable for first-time buyers):")
print(sorted_counties[["RegionName", "Average_Bottom_Tier_ZHVI"]].head(10).to_markdown(index=False))

Top counties with positive bottom-tier ZHVI aggregates (affordable for first-time buyers):
|   RegionName |   Average_Bottom_Tier_ZHVI |
|-------------:|---------------------------:|
|        75220 |                   0.833333 |
|        75209 |                   0.533333 |
|        75230 |                   0.5      |
|        75229 |                   0.5      |
|        75246 |                   0.433333 |
|        75218 |                   0.433333 |
|        75244 |                   0.433333 |
|        75238 |                   0.333333 |
|        75201 |                   0.3      |
|        75214 |                   0.266667 |

C:\Users\megha\AppData\Local\Temp\ipykernel_4180\767998726.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dallas_zips["Average_Bottom_Tier_ZHVI"] = dallas_zips[zhvi_columns].mean(axis=1)

In [36]:
growth_cols = [c for c in df_zhvf_growth.columns if c.startswith("2025") or c.startswith("2026")]

In [37]:
df_zhvf_growth["TotalGrowth"] = df_zhvf_growth[growth_cols].sum(axis=1)

In [38]:
df_zhvf_growth["Stability"] = 1 / (df_zhvf_growth[growth_cols].std(axis=1) + 1e-6)  # Adding a small constant to avoid division by zero

In [39]:

df_zhvf_growth["AvgGrowth"] = df_zhvf_growth[growth_cols].mean(axis=1)

In [40]:
def normalize(x):
    return (x - x.min()) / (x.max() - x.min())

df_zhvf_growth["Growth_norm"] = normalize(df_zhvf_growth["AvgGrowth"])
df_zhvf_growth["Total_norm"]  = normalize(df_zhvf_growth["TotalGrowth"])
df_zhvf_growth["Stable_norm"] = normalize(df_zhvf_growth["Stability"])

In [41]:
df_zhvf_growth["ZipScore"] = (
    0.50 * df_zhvf_growth["Growth_norm"] +
    0.30 * df_zhvf_growth["Stable_norm"] +
    0.20 * df_zhvf_growth["Total_norm"]
)

In [42]:

df_dallas = df_zhvf_growth[(df_zhvf_growth['City'] == "Dallas") & (df_zhvf_growth['State'] == "TX")]
df_ranked = df_dallas.sort_values("ZipScore", ascending=False)

df_ranked[["RegionName", "CountyName", "ZipScore", "Growth_norm", "Stable_norm","Total_norm"]].head(20)

,RegionName,CountyName,ZipScore,Growth_norm,Stable_norm,Total_norm
1471,75220,Dallas County,0.525001,0.750000,3.818058e-06,0.750000
7676,75209,Dallas County,0.509714,0.728155,1.716469e-05,0.728155
4837,75230,Dallas County,0.508011,0.725728,5.617946e-06,0.725728
3008,75229,Dallas County,0.508011,0.725728,3.624107e-06,0.725728
8321,75244,Dallas County,0.504613,0.720874,4.648298e-06,0.720874
5172,75218,Dallas County,0.504613,0.720874,3.117734e-06,0.720874
15582,75246,Dallas County,0.504612,0.720874,1.153782e-06,0.720874
3347,75238,Dallas County,0.499515,0.713592,2.485822e-06,0.713592
7042,75201,Dallas County,0.497816,0.711165,3.177799e-06,0.711165
3094,75214,Dallas County,0.496118,0.708738,4.174585e-06,0.708738
2205,75206,Dallas County,0.489326,0.699029,1.716469e-05,0.699029
5271,75240,Dallas County,0.484224,0.691748,3.308566e-06,0.691748
2391,75248,Dallas County,0.484224,0.691748,2.485822e-06,0.691748
7834,75223,Dallas County,0.484224,0.691748,1.153782e-06,0.691748
3293,75204,Dallas County,0.482526,0.689320,5.617946e-06,0.689320
3229,75208,Dallas County,0.474030,0.677184,2.485822e-06,0.677184
5277,75219,Dallas County,0.472332,0.674757,4.844452e-06,0.674757
7521,75215,Dallas County,0.472330,0.674757,8.814268e-07,0.674757
167,75228,Dallas County,0.468933,0.669903,3.117734e-06,0.669903
7037,75236,Dallas County,0.463836,0.662621,3.818058e-06,0.662621